### ISSUE TITLE
Autolab Issue

### ISSUE THREAD

**Issue by DanLarsen-COSF** [pluralsight/PS-AutoLab-Env#109]
Hello,
I am working on your Certs course and I have not been able to to get the Autolab portion with Multiple servers to work - The VM completion test never seems to pass after I run unattend-lab. Are their some logs I can send you to tell me what I can do to allow the lab to be built so I can continue the course? Thanks!

**Comment by jdhitsolutions** [comment]
We need better logging no doubt about it. It is possible that everything works now.  What configuration are you using? The configurations can take longer than you think to converge. My suggestion is to open PowerShell (elevated). Change to the configuration directory. Run Get-VM. If you see any virtual machines for the configuration and they are running try running Validate-Lab to see if anything passes. Are there MOFs in the directory? 

The only other suggestion I have is to wipe the lab, and run the steps outlined in Instructions.md instead of running it unattended.
