### ISSUE TITLE
How do you stop if from trying to download the ISO's  everytime?

### ISSUE THREAD

**Issue by DerakW** [pluralsight/PS-AutoLab-Env#218]
I successfully deployed the multirole lab to my laptop.  Tried to copy the ISO's to another computer, yet it still tries to download them.  Is there a way to bypass this and just use the ISO's I already downloaded?

**Comment by jdhitsolutions** [comment]
The ISO files must not only have the expected name, but there also needs to be a checksum file. But if you installed Autolab on one computer and setup a lab to download the isos, then setup Autolab on another computer and then copied the files over, that *should* work.  Unless something happened in the copy and the checksum broke. But since you closed this I'm assuming this isn't something we need to pursue.
