### ISSUE TITLE
Test for Lability Version

### ISSUE THREAD

**Issue by jdhitsolutions** [pluralsight/PS-AutoLab-Env#46]
In Setup-Host it is possible that someone might have an older version of Lability installed. Even though the script is downloading 0.10.1 it won't remove any previous versions and later when commands from the module are invoked, there is no guarantee about which version will be called. 

I suggest in Setup-Host testing if the require version of Lability is installed. If there are any older versions STOP and ask the user to remove them then re-rerun Setup-Host If the version is the same, then skip installing otherwise install it

**Comment by jdhitsolutions** [comment]
If the user has an older version of Lability we might also recommend they restart PowerShell after uninstalling. I've run into caching issues where the old version was still getting called even after uninstalling the module.

**Comment by jdhitsolutions** [comment]
Here is a function you might consider using to test if Lability is installed.
[Test-Module.txt](https://github.com/theJasonHelmick/PS-AutoLab-Env/files/579681/Test-Module.txt)

**Comment by theJasonHelmick** [comment]
Can you maybe add this to the new module?  Have it read the current lability version from Config Data (which I dont have in there yet) and remove all others?  What we really need to do is have it run for each config --- read the DSCReources for the config and remove older modules....xNetworking bit me in the ass because of this... @jdhitsolutions @majst32

**Comment by theJasonHelmick** [comment]
@jdhitsolutions didn't we already fix this?  I will check.
