### ISSUE TITLE
Parameter for Snapshot-Lab

### ISSUE THREAD

**Issue by themichaelbender** [pluralsight/PS-AutoLab-Env#72]
Would it be possible to have a parameter added to allow custom naming of the snapshots for the Snapshot-Lab command? I'd like to create a temporary snapshot after each module.

**Comment by jdhitsolutions** [comment]
You can create snapshots at any time with the Hyper-V cmdlets. I'd say the Snapshot-Lab command is a convenience and makes it easier to roll back the entire lab. I think what you really want is a Snapshot-Lab [-snapshotname <string>] and a corresponding Rollback-Lab [-snapshotname <string>]. I say go for it and submit a PR!

**Comment by themichaelbender** [comment]
If you can point me to where the code for those commands is located, I'll work on it after my course is done. I have a workaround now using the Hyper-V cmdlets.

**Comment by jdhitsolutions** [comment]
https://github.com/theJasonHelmick/PS-AutoLab-Env/blob/master/Tools/PSAutoLab/PSAutoLab.psm1

**Comment by jdhitsolutions** [comment]
Those changes look pretty easy to make since the underlying commands already take a parameter value for a snapshot name. All we (you) need to do is add a SnapshotName parameter and set a default value using the current setting. That won't break anything and still allow us to snapshot at anytime with a new name. Although, now that I think about it, there would need to be some logic to check if there is an existing snapshot with the same name.

**Comment by themichaelbender** [comment]
Got it!

I'll see what I can come up with.

Thanks!

Michael Bender
-via mobile device

________________________________

**Comment by theJasonHelmick** [comment]
Status? Currently working on new version

**Comment by themichaelbender** [comment]
Dropped the ball and forgot about this. I will take a look and see what I can come up with. Won't be till last week of June as I'm offline most of the next two weeks.

**Comment by theJasonHelmick** [comment]
Actually my friend, don't worry about it. I got it on my list so I will explore it for the future release.
